// Track lists are generated by scripts/build-playlists.mjs and committed, so the
// catalog is fixed at build time and the daily pick can't drift when Deezer
// reorders a chart. Preview URLs are fetched per round (they expire quickly).
//
// Only the small index is bundled up front — roughly 2000 track records would
// otherwise sit in the initial download — so the lists load on demand.

import type { Track } from '../lib/deezer'
import type { ClipMode } from '../lib/game'
import index from './generated/index.json'

export type PlaylistInfo = {
  id: string
  title: string
  emoji: string
  count: number
  /** How many of the tracks have a YouTube id, i.e. are playable in intro mode. */
  introCount: number
  /** Daily pool only: every track works in either clip mode. */
  bothModes?: boolean
}

export type Playlist = PlaylistInfo & { tracks: Track[] }

// Discovered rather than listed, so adding a playlist to scripts/sources.mjs is
// all it takes — there is no second place to remember to update. Vite turns each
// match into its own lazily-loaded chunk.
const loaders = import.meta.glob<{ default: { tracks: Track[] } }>('./generated/*.json')

/**
 * Daily songs are assigned to dates at build time and frozen, so rebuilding the
 * catalog can't change which song a given date plays. Loaded on demand — it is
 * only needed once someone starts the daily challenge.
 */
export async function loadDailyTrack(date: string): Promise<Track | null> {
  const schedule = (await import('./generated/daily-schedule.json')).default as Record<
    string,
    Track
  >
  return schedule[date] ?? null
}

export const PLAYLISTS: PlaylistInfo[] = index.playlists

export const DAILY_INFO: PlaylistInfo = index.daily

const cache = new Map<string, Playlist>()

export async function loadPlaylist(info: PlaylistInfo): Promise<Playlist> {
  const cached = cache.get(info.id)
  if (cached) return cached

  const loader = loaders[`./generated/${info.id}.json`]
  if (!loader) throw new Error(`Unknown playlist "${info.id}"`)

  const module = (await loader()) as { default: { tracks: Track[] } }
  const playlist: Playlist = { ...info, tracks: module.default.tracks }
  cache.set(info.id, playlist)
  return playlist
}

/** Intro mode can only use tracks that were matched to a YouTube video. */
export const tracksForMode = (playlist: Playlist, clipMode: ClipMode): Track[] =>
  clipMode === 'intro' ? playlist.tracks.filter((t) => t.youtubeId) : playlist.tracks

/**
 * A handful of mapped tracks would mean replaying the same few songs, so a
 * playlist only counts as intro-ready once it has a workable spread.
 */
const MIN_INTRO_TRACKS = 30

export const supportsIntro = (info: PlaylistInfo) => info.introCount >= MIN_INTRO_TRACKS

/**
 * The daily is stricter: unless every track in the pool plays in either mode,
 * Hook and Intro players would be given different songs on the same date.
 */
export const dailySupportsIntro = () => DAILY_INFO.bothModes === true
